### ISSUE TITLE
API setup

### ISSUE THREAD

**Issue by s32989** [s32989/tarot_journal#2]
Use postman to make a GET request to localhost:XXXX/api/helloworld and it returns our message from database

**Comment by cobbettn** [comment]
@s32989  Didn't make a PR for this, I was devving on main since this is still exploratory stuff. Otherwise I would have linked a PR to this issue. From now on we should start creating new branches for each issue we work on.

This should be testable after you delete your collection and add a new one named `messages` that includes the data you added initially. 

You can just use your browser to test for now but we will be setting up a postman collection for our API in the near future which is what we will use going forward

after you have the API running go to http://localhost:3000/hello or http://localhost:3000/hello/another-route and confirm that we you see the message

**Comment by cobbettn** [comment]
@s32989 FYI we should move these issues into the done column when closed
